# Generated by Django 4.2.5 on 2023-09-26 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_description'),
        ('main', '0002_item'),
    ]

    operations = [
    ]
